# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '13.0'

target 'SuprSendSdk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  #Pods for SuprSendSdk
  pod 'SuprsendCore', '1.0.2'

end
